import type { Metadata } from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "replicate-stream",
  description: "Generated by appncy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className=" py-5 text-center text-6xl  font-bold leading-[4rem]">
          <Link href="/">Your photo as a Disney character</Link>
        </header>
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
